---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: no
configure_terminal: no
configure_osx: yes

dotfiles_repo: https://github.com/uschti/dotfiles-default.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/.dotfiles-default
dotfiles_files:
  - .macos
  - .screenrc

homebrew_installed_packages:
  - ffmpeg
  - git
  - gpg
  - openssl
  - wget

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - caskroom/versions
  - caskroom/drivers

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - avg-antivirus
  - adobe-acrobat-reader
  - caffeine
  - cyberduck
  - dropbox
  - java8
  - firefox
  - gimp
  - google-chrome
  - google-earth-pro
  - image2icon
  - istat-menus
  - libreoffice
  - keepassxc
  - keka
  - synology-drive
  - nextcloud
  - skype
  - smcfancontrol
  - thunderbird
  - tunnelblick
  - vmware-fusion
  - vlc
  - whatsapp
  - youtube-to-mp3

mas_installed_apps:
  - { id: 497799835, name: "Xcode (9.3)"}
  - { id: 425955336, name : "Skitch (2.8.1)"}
  - { id: 409183694, name: "Keynote (7.3.1)"}
  - { id: 409203825, name: "Numbers (5.0)"}
  - { id: 409201541, name: "Pages (7.0)"}
  - { id: 404010395, name: "TextWrangler (5.5.2)"}
  - { id: 458887729, name: "Translate Tab (2.0.1)"}

mas_email: ""
mas_password: ""

osx_script: "~/.dotfiles-default/.osx --no-restart"

# Create some useful directory structures
required_directories:
  - "~/.ansible/roles"
  - "~/cloud"
  - "~/VM"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []

pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
